"""Initial migration

Revision ID: 4a0d420933fc
Revises: 
Create Date: 2025-08-02 18:06:44.698516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0d420933fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividades',
    sa.Column('id_atividade', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_de_servico', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('quem', sa.String(length=255), nullable=True),
    sa.Column('armazenna', sa.String(length=255), nullable=True),
    sa.Column('empresa', sa.String(length=255), nullable=True),
    sa.Column('data', sa.String(length=255), nullable=True),
    sa.Column('STATUS', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_atividade')
    )
    op.create_table('funcionarios_cadastrados',
    sa.Column('id_funcionario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=255), nullable=True),
    sa.Column('funcao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_funcionario')
    )
    op.create_table('registro',
    sa.Column('id_registro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_atividade', sa.Integer(), nullable=True),
    sa.Column('legenda', sa.String(length=255), nullable=True),
    sa.Column('img', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_table('frequencia',
    sa.Column('id_frequencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('data', sa.String(length=255), nullable=True),
    sa.Column('hora', sa.String(length=255), nullable=True),
    sa.Column('funcao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionarios_cadastrados.id_funcionario'], ),
    sa.PrimaryKeyConstraint('id_frequencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequencia')
    op.drop_table('registro')
    op.drop_table('funcionarios_cadastrados')
    op.drop_table('atividades')
    # ### end Alembic commands ###
